
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_FAIL='SIGNUP_FAIL';
export const UPDATE_SUCCESS='UPDATE_SUCCESS';
export const UPDATE_FAIL='UPDATE_FAIL';