
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_FAIL='SIGNUP_FAIL';
export const UPDATE_SUCCESS='UPDATE_SUCCESS';
export const UPDATE_FAIL='UPDATE_FAIL';
export const GET_PROFILE_SUCCESS='GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL='GET_PROFILE_FAIL';
export const SET_PROFILE_SUCCESS='SET_PROFILE_SUCCESS';
export const SET_PROFILE_FAIL='SET_PROFILE_FAIL';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';
export const LOGOUT_FAIL='LOGOUT_FAIL';